name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: setup cache
      uses: actions/cache@v3.2.3
      with:
        path: venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('setup.cfg') }}

    - name: install
      run: make install

    - name: lint
      run: make lint

    - name: mypy
      run: make mypy

    - name: test
      run: make test
